### PR TITLE
Target net46

### PR DESCRIPTION
**Pull request by ablanchet**
Fixes issue #41 

:warning:  We need to ugrade [Zebus.Directory](https://github.com/Abc-Arbitrage/Zebus.Directory) too !

### CODE REVIEW

**Comment by ablanchet** [comment]
I've just made a little test: a .NET 4.5 console application trying to reference a .NET 4.6 assembly. The result was predictable, the .NET 4.5 console has two warnings when trying to build :

```
- The primary reference "c:\users\antoine\documents\visual studio 2015\Projects\Net46\Net46\bin\Debug\Net46.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".	
- The referenced project 'Net46' is targeting a higher framework version (4.6) than this project’s current target framework version (4.5). This may lead to build failures if types from assemblies outside this project’s target framework are used by any project in the dependency chain.
```

We will have to ship a Zebus Nuget package with two targetable frameworks (net45 & net46), or upgrade all our services.		
The second solution seems heavy but it's always a good idea to upgrade to the latest version of the framework :smile:

**Comment by alprema** [comment]
As much as I would like to move to the latest version of the framework, we should consider postponing this to a major version since this is definitely a breaking change.

**Comment by ablanchet** [comment]
I don't know. The next major version would be 2.0 and I think we need more "new features" or refactorings in order to justify a new major release.

It's purely cosmetic but I think a C# 6 + .NET 4.6 Zebus (+Directory) would be fine in a 1.5 version.

We should keep the 2.0 version for a greater breaking change, like a 'Zmq-less' or a 'protobuf-less' version :smiley:.

**Comment by ablanchet** [comment]
FYI I've just pushed a PR on Zebus.Directory for the .NET 4.6 migration ([here](https://github.com/Abc-Arbitrage/Zebus.Directory/pull/3)).

**Comment by ablanchet** [comment]
Postponed to .net 4.7.x when needed

**Pull request closed without merging**
