### PR TITLE
Dependency injection using Lamar

### PR DESCRIPTION
**Pull request by alexandrekow**
The goal of this pull request is to be able to replace `StructureMap` by `Lamar`.
This pull request introduces a `IDependencyInjectionContainerProvider` to be used to get a container from a dependency injection framework. It also introduces a `LamarZebusRegistry`.
I am able to run a Zebus Host on my machine with `Lamar`. 

To facilitate the migration from StructureMap to Lamar, having both the `StructureMap` and the  `Lamar` packages might be helpful, or we might want to create a new breaking change version. 

- @ltrzesniewski I would like your opinion, especially about the changes in `MessageHandlerInvoker.cs`

### CODE REVIEW

**Comment by MendelMonteiro** [comment]
I'm assuming that the StructureMap build plans were cached for performance reasons and if so this will lead to a performance regression as the implementation in this PR is the same as what was present before [the commit that introduced the caching](https://github.com/Abc-Arbitrage/Zebus/commit/013d3f8a61ca227baf13974bdd40a16266816f08#diff-9e1d68b7254bb345be175905b15d140edfc8a821a4089bb8eccfa683dcd3cac8L67).

The Lamar implementation should also be measured to see what the perf is relative to the previous implementation.  Also, do we need to create a nested container?  Is there a performance cost associated?

**Comment by ltrzesniewski** [comment]
> I'm assuming that the StructureMap build plans were cached for performance reasons and if so this will lead to a performance regression as the implementation in this PR is the same as what was present before [the commit that introduced the caching](https://github.com/Abc-Arbitrage/Zebus/commit/013d3f8a61ca227baf13974bdd40a16266816f08#diff-9e1d68b7254bb345be175905b15d140edfc8a821a4089bb8eccfa683dcd3cac8L67).

Yes, that part is perf-critical as it's on the hot path. The code which cached the instance build plan is ugly, but IIRC it improved the throughput *a lot*.



> The Lamar implementation should also be measured to see what the perf is relative to the previous implementation. Also, do we need to create a nested container? Is there a performance cost associated?

:+1:

**Comment by ltrzesniewski** [comment]
Also, what's the migration plan? I don't really like having to reference two distinct IoC containers. It would be really easy to mess something up down the road (libraries referenced by Zebus are propagated *everywhere*).

**Comment by ltrzesniewski** [comment]
Maybe we could reference only Lamar from Zebus, and provide a shim from StructureMap to Lamar internally (reimplement the part of the StructureMap API surface we use on top of Lamar)?

That would be quite a big bang change though.

**Comment by ocoanet** [comment]
Removing the `StructureMap` dependency seems to be a good idea. But it might be better to reference a container abstraction instead. Did we decide to switch to Lamar in a GitHub issue or an internal discussion?

**Comment by alexandrekow** [comment]
Thanks for the comments guys 😃

I will reply to them by theme.

### Migration 🗺️  
> Also, what's the migration plan? 
> Did we decide to switch to Lamar in a GitHub issue or an internal discussion?

We talked about it internally informally a long time ago. 
One year ago, I decided to try and see if it would be easy to replace `StructureMap` by `Lamar`. Then the code was left sleeping on my computer. 
Recently I stumbled into this code and thought it might be interesting to share it to get some feedback even though it is not fully completed (hence the **Draft PR**).

As @ltrzesniewski pointed out, if we want to migrate, it would be better to avoid referencing the two librairies at the same time. 

### Performance 🚀 

> The Lamar implementation should also be measured to see what the perf is relative to the previous implementation. 

I quote [Lamar's documentation](https://jasperfx.github.io/lamar/guide/) :

> Lamar was conceived as a replacement for StructureMap that would **hugely improve** upon StructureMap's performance
  
Even though the documentation implies the performance should be better, I totally agree that we should measure it before making the switch.

> Yes, that part is perf-critical as it's on the hot path. The code which cached the instance build plan is ugly, but IIRC it improved the throughput by _a lot_.

@ltrzesniewski do you happen to remember which benchmark you ran to measure the throughput? It might be helpful to use the same one if you still have it.
 
### Nested container :package:
> Also, do we need to create a nested container? Is there a performance cost associated?

@MendelMonteiro are you referring to the `_lamarContainer.GetNestedContainer()` call in the `GetMessageHandlerInstance`?  

### Abstraction 🏗️ 
> But it might be better to reference a container abstraction instead

@ocoanet do you mean it would be better to reference `IDependencyInjectionContainer` directly instead of `IDependencyInjectionContainerProvider`?


### TODO 🚧 👷 

Now, I can see that there is still some work to do if we would like to migrate. 

- [ ] Compare `StructureMap` vs `Lamar` performances
- [ ] Put back the cache in `MessageHandlerInvoker` to at least avoid performance regression with `StructureMap` 
- [ ] Try to use a container abstraction directly
- [ ] Find a way to avoid referencing `StructureMap` and `Lamar` at the same time
- [ ] Work on a migration plan

**Comment by MendelMonteiro** [comment]
> @MendelMonteiro are you referring to the _lamarContainer.GetNestedContainer() call in the GetMessageHandlerInstance?

Yep

**Comment by ltrzesniewski** [comment]
> do you happen to remember which benchmark you ran to measure the throughput? It might be helpful to use the same one if you still have it.

Sorry, that was a long time ago 😕

**Comment by alexandrekow** [comment]
I am closing this PR as we concluded Lamar was not a good fit for our platform.

**Pull request closed without merging**
